### ISSUE TITLE
Milestone #1

### ISSUE THREAD

**Issue by pguth** [pguth/timefs#1]
- [ ] webrtc room, negotiation
 - [ ] gossip, hash-of-past, find diffs, sync
 - [ ] display, calculate metrics
